# Generated by Django 2.2.5 on 2020-08-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20200811_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(default='blabla', max_length=300),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(default='bla', max_length=200),
        ),
    ]
