# Generated by Django 2.2 on 2020-08-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
    ]
