# Generated by Django 2.2 on 2020-08-17 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
    ]
