# Generated by Django 2.2 on 2020-08-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20200818_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Company', max_length=200, null=True),
        ),
    ]
