# Generated by Django 2.2 on 2020-08-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_auto_20200818_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shops.Shop'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('shop', 'name')},
        ),
    ]
