# Generated by Django 2.2 on 2020-08-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_auto_20200818_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shops.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('company', 'name')},
        ),
        migrations.RemoveField(
            model_name='company',
            name='shop',
        ),
    ]
