# Generated by Django 2.2 on 2020-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_auto_20200818_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='shop_id',
            field=models.IntegerField(null=True),
        ),
    ]
