# Generated by Django 2.2 on 2020-08-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_company_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='shop_id',
        ),
        migrations.AlterField(
            model_name='shop',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set(),
        ),
    ]
