# Generated by Django 2.2 on 2020-08-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20200825_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='test',
            field=models.IntegerField(default=14, null=True),
        ),
    ]
